# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'window.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLayout,
    QSizePolicy, QVBoxLayout, QWidget)
import resources_rc

class Ui_Runstats(object):
    def setupUi(self, Runstats):
        if not Runstats.objectName():
            Runstats.setObjectName(u"Runstats")
        Runstats.resize(571, 708)
        self.widget = QWidget(Runstats)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 571, 491))
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.title_label = QLabel(self.widget)
        self.title_label.setObjectName(u"title_label")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.title_label.setFont(font)
        self.title_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.title_label)

        self.coordinates = QWidget(self.widget)
        self.coordinates.setObjectName(u"coordinates")
        self.coordinates.setEnabled(True)
        self.coordinates.setMaximumSize(QSize(16777215, 200))
        self.hp = QFrame(self.coordinates)
        self.hp.setObjectName(u"hp")
        self.hp.setGeometry(QRect(8, 59, 571, 61))
        self.hp_location = QLabel(self.hp)
        self.hp_location.setObjectName(u"hp_location")
        self.hp_location.setGeometry(QRect(52, 10, 160, 51))
        sizePolicy.setHeightForWidth(self.hp_location.sizePolicy().hasHeightForWidth())
        self.hp_location.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setPointSize(15)
        self.hp_location.setFont(font1)
        self.hp_location.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.hp_location.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.nether_portal = QLabel(self.hp)
        self.nether_portal.setObjectName(u"nether_portal")
        self.nether_portal.setGeometry(QRect(6, 10, 40, 51))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.nether_portal.sizePolicy().hasHeightForWidth())
        self.nether_portal.setSizePolicy(sizePolicy1)
        self.nether_portal.setMinimumSize(QSize(0, 0))
        self.nether_portal.setPixmap(QPixmap(u":/images/Assets/nether_portal.png"))
        self.nether_portal.setScaledContents(True)
        self.hp_distance = QLabel(self.hp)
        self.hp_distance.setObjectName(u"hp_distance")
        self.hp_distance.setGeometry(QRect(212, 10, 160, 51))
        sizePolicy.setHeightForWidth(self.hp_distance.sizePolicy().hasHeightForWidth())
        self.hp_distance.setSizePolicy(sizePolicy)
        self.hp_distance.setFont(font1)
        self.hp_distance.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.hp_distance.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.hp_angle = QLabel(self.hp)
        self.hp_angle.setObjectName(u"hp_angle")
        self.hp_angle.setGeometry(QRect(372, 10, 160, 51))
        sizePolicy.setHeightForWidth(self.hp_angle.sizePolicy().hasHeightForWidth())
        self.hp_angle.setSizePolicy(sizePolicy)
        self.hp_angle.setFont(font1)
        self.hp_angle.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.hp_angle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.location = QLabel(self.coordinates)
        self.location.setObjectName(u"location")
        self.location.setGeometry(QRect(60, 0, 160, 41))
        sizePolicy.setHeightForWidth(self.location.sizePolicy().hasHeightForWidth())
        self.location.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setPointSize(15)
        font2.setBold(True)
        self.location.setFont(font2)
        self.location.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.location.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.compass = QLabel(self.coordinates)
        self.compass.setObjectName(u"compass")
        self.compass.setGeometry(QRect(10, 0, 51, 50))
        self.compass.setMinimumSize(QSize(0, 0))
        self.compass.setPixmap(QPixmap(u":/images/Assets/compass.png"))
        self.compass.setScaledContents(True)
        self.line = QFrame(self.coordinates)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 38, 571, 30))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.dist = QLabel(self.coordinates)
        self.dist.setObjectName(u"dist")
        self.dist.setGeometry(QRect(220, 0, 160, 41))
        sizePolicy.setHeightForWidth(self.dist.sizePolicy().hasHeightForWidth())
        self.dist.setSizePolicy(sizePolicy)
        self.dist.setFont(font2)
        self.dist.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.dist.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.angle = QLabel(self.coordinates)
        self.angle.setObjectName(u"angle")
        self.angle.setGeometry(QRect(380, 0, 160, 41))
        sizePolicy.setHeightForWidth(self.angle.sizePolicy().hasHeightForWidth())
        self.angle.setSizePolicy(sizePolicy)
        self.angle.setFont(font2)
        self.angle.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.angle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.coords_2 = QFrame(self.coordinates)
        self.coords_2.setObjectName(u"coords_2")
        self.coords_2.setGeometry(QRect(8, 120, 571, 71))
        self.coords_2_location = QLabel(self.coords_2)
        self.coords_2_location.setObjectName(u"coords_2_location")
        self.coords_2_location.setGeometry(QRect(52, 10, 160, 51))
        sizePolicy.setHeightForWidth(self.coords_2_location.sizePolicy().hasHeightForWidth())
        self.coords_2_location.setSizePolicy(sizePolicy)
        self.coords_2_location.setFont(font1)
        self.coords_2_location.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.coords_2_location.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.coords_2_icon = QLabel(self.coords_2)
        self.coords_2_icon.setObjectName(u"coords_2_icon")
        self.coords_2_icon.setGeometry(QRect(0, 10, 51, 50))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.coords_2_icon.sizePolicy().hasHeightForWidth())
        self.coords_2_icon.setSizePolicy(sizePolicy2)
        self.coords_2_icon.setMinimumSize(QSize(0, 0))
        self.coords_2_icon.setPixmap(QPixmap(u":/images/Assets/recovery_compass.png"))
        self.coords_2_icon.setScaledContents(True)
        self.coords_2_distance = QLabel(self.coords_2)
        self.coords_2_distance.setObjectName(u"coords_2_distance")
        self.coords_2_distance.setGeometry(QRect(212, 10, 160, 51))
        sizePolicy.setHeightForWidth(self.coords_2_distance.sizePolicy().hasHeightForWidth())
        self.coords_2_distance.setSizePolicy(sizePolicy)
        self.coords_2_distance.setFont(font1)
        self.coords_2_distance.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.coords_2_distance.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.coords_2_angle = QLabel(self.coords_2)
        self.coords_2_angle.setObjectName(u"coords_2_angle")
        self.coords_2_angle.setGeometry(QRect(372, 10, 160, 51))
        sizePolicy.setHeightForWidth(self.coords_2_angle.sizePolicy().hasHeightForWidth())
        self.coords_2_angle.setSizePolicy(sizePolicy)
        self.coords_2_angle.setFont(font1)
        self.coords_2_angle.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.coords_2_angle.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.coordinates)

        self.fort = QWidget(self.widget)
        self.fort.setObjectName(u"fort")
        self.fort_icon = QLabel(self.fort)
        self.fort_icon.setObjectName(u"fort_icon")
        self.fort_icon.setGeometry(QRect(10, 70, 51, 50))
        sizePolicy2.setHeightForWidth(self.fort_icon.sizePolicy().hasHeightForWidth())
        self.fort_icon.setSizePolicy(sizePolicy2)
        self.fort_icon.setMinimumSize(QSize(0, 0))
        self.fort_icon.setPixmap(QPixmap(u":/images/Assets/fortress.png"))
        self.fort_icon.setScaledContents(True)
        self.direction = QLabel(self.fort)
        self.direction.setObjectName(u"direction")
        self.direction.setGeometry(QRect(60, 20, 131, 41))
        sizePolicy.setHeightForWidth(self.direction.sizePolicy().hasHeightForWidth())
        self.direction.setSizePolicy(sizePolicy)
        self.direction.setFont(font2)
        self.direction.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.direction.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.chunks = QLabel(self.fort)
        self.chunks.setObjectName(u"chunks")
        self.chunks.setGeometry(QRect(60, 110, 131, 41))
        sizePolicy.setHeightForWidth(self.chunks.sizePolicy().hasHeightForWidth())
        self.chunks.setSizePolicy(sizePolicy)
        self.chunks.setFont(font2)
        self.chunks.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.chunks.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.fort_direction = QLabel(self.fort)
        self.fort_direction.setObjectName(u"fort_direction")
        self.fort_direction.setGeometry(QRect(60, 60, 131, 51))
        sizePolicy.setHeightForWidth(self.fort_direction.sizePolicy().hasHeightForWidth())
        self.fort_direction.setSizePolicy(sizePolicy)
        self.fort_direction.setFont(font1)
        self.fort_direction.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.fort_direction.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.fort_quadrant = QLabel(self.fort)
        self.fort_quadrant.setObjectName(u"fort_quadrant")
        self.fort_quadrant.setGeometry(QRect(240, 0, 261, 231))
        self.fort_chunks = QLabel(self.fort)
        self.fort_chunks.setObjectName(u"fort_chunks")
        self.fort_chunks.setGeometry(QRect(60, 150, 131, 51))
        sizePolicy.setHeightForWidth(self.fort_chunks.sizePolicy().hasHeightForWidth())
        self.fort_chunks.setSizePolicy(sizePolicy)
        self.fort_chunks.setFont(font1)
        self.fort_chunks.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.fort_chunks.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.fort)


        self.retranslateUi(Runstats)

        QMetaObject.connectSlotsByName(Runstats)
    # setupUi

    def retranslateUi(self, Runstats):
        Runstats.setWindowTitle(QCoreApplication.translate("Runstats", u"Runstats", None))
        self.title_label.setText(QCoreApplication.translate("Runstats", u"Runstats - Developed by smeks", None))
        self.hp_location.setText("")
        self.nether_portal.setText("")
        self.hp_distance.setText("")
        self.hp_angle.setText("")
        self.location.setText(QCoreApplication.translate("Runstats", u"Location", None))
        self.compass.setText("")
        self.dist.setText(QCoreApplication.translate("Runstats", u"Distance", None))
        self.angle.setText(QCoreApplication.translate("Runstats", u"Angle", None))
        self.coords_2_location.setText("")
        self.coords_2_icon.setText("")
        self.coords_2_distance.setText("")
        self.coords_2_angle.setText("")
        self.fort_icon.setText("")
        self.direction.setText(QCoreApplication.translate("Runstats", u"Direction", None))
        self.chunks.setText(QCoreApplication.translate("Runstats", u"Chunks", None))
        self.fort_direction.setText(QCoreApplication.translate("Runstats", u"North", None))
        self.fort_quadrant.setText("")
        self.fort_chunks.setText(QCoreApplication.translate("Runstats", u"16", None))
    # retranslateUi

